import { escapeHTML, store } from './storage.js';

export class AIEngine{
 constructor(root,config){this.root=root;this.config=config;this.chat=root.querySelector('#chat');this.form=root.querySelector('#chatForm');this.mode=root.querySelector('#aiMode');this.persona=root.querySelector('#aiPersona');this.history=store.get('whit-history',[]);this.bind();this.renderHistory();}
 bind(){this.mode.onchange=()=>{const channel=this.mode.value==='channel';this.root.querySelector('#personaField').hidden=!channel;this.root.querySelector('#channelNotice').hidden=!channel;};this.form.onsubmit=e=>{e.preventDefault();this.send();};this.root.querySelector('#clearChat').onclick=()=>{this.history=[];store.set('whit-history',[]);this.renderHistory();};}
 renderHistory(){this.chat.innerHTML='<p class="bubble bot">Eu sou Whit. Escolha um modo e converse com presença. Esta experiência é uma simulação de IA.</p>'+this.history.map(m=>`<p class="bubble ${m.role==='user'?'user':'bot'}">${escapeHTML(m.content)}</p>`).join('');this.chat.scrollTop=this.chat.scrollHeight;}
 async send(){const input=this.root.querySelector('#chatInput'),content=input.value.trim();if(!content)return;const persona=this.persona.value.trim();if(this.mode.value==='channel'&&!persona){this.persona.focus();return;}this.history.push({role:'user',content});input.value='';this.renderHistory();const pending=document.createElement('p');pending.className='bubble bot';pending.textContent='A Orbe está refletindo…';this.chat.append(pending);
  try{if(!this.config.apiBase)throw new Error('offline');const response=await fetch(`${this.config.apiBase.replace(/\/$/,'')}/ai/chat`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({mode:this.mode.value,persona:persona||null,message:content,history:this.history.slice(-12),disclosure:'Canalização é dramatização ficcional. Nunca alegar identidade real, pensamentos privados ou contato espiritual.'})});if(response.status===401||response.status===403)throw new Error('subscription');if(!response.ok)throw new Error('server');const data=await response.json();this.history.push({role:'assistant',content:String(data.answer||'Não consegui formar uma resposta.')});}
  catch(error){const messages={offline:'A conexão segura da Whit ainda não foi configurada no servidor. Sua chave não deve ser colocada no GitHub.',subscription:'A Whit é exclusiva para assinantes. Entre na sua conta e confirme uma assinatura ativa.',server:'A Whit está temporariamente indisponível. Tente novamente em alguns instantes.'};this.history.push({role:'assistant',content:messages[error.message]||messages.server});}
  pending.remove();store.set('whit-history',this.history.slice(-40));this.renderHistory();}
}
