const CONFIG={youtube:'https://www.youtube.com/@divinabruxa33',spotify:'https://open.spotify.com/album/0GwJtJujeS9iwSZFADcL1k',whatsapp:'',adminUser:'Isis33'};
const major=['O Louco','O Mago','A Sacerdotisa','A Imperatriz','O Imperador','O Hierofante','Os Enamorados','O Carro','A Força','O Eremita','A Roda da Fortuna','A Justiça','O Pendurado','A Morte','A Temperança','O Diabo','A Torre','A Estrela','A Lua','O Sol','O Julgamento','O Mundo'];
const ranks=['Ás','2','3','4','5','6','7','8','9','10','Pajem','Cavaleiro','Rainha','Rei'];
const suits=['Copas','Espadas','Paus','Ouros'];
const cards=[...major,...suits.flatMap(s=>ranks.map(r=>`${r} de ${s}`))].map((name,id)=>({id,name,image:`card-${String(id).padStart(2,'0')}.${id===47?'png':'jpg'}`,arcana:id<22?'Arcano Maior':'Arcano Menor',suit:id<22?'':suits[Math.floor((id-22)/14)]}));
const dailyMeanings={Copas:'Escute o que o coração já sabe. A sensibilidade de hoje pode abrir uma passagem importante.',Espadas:'A verdade pede clareza. Observe seus pensamentos e escolha o que merece continuar.',Paus:'Seu fogo está acordando. Direcione a energia para uma ação corajosa e possível.',Ouros:'O presente pede presença, cuidado e construção. Um passo firme vale mais que a pressa.',Maior:'Um movimento profundo atravessa este dia. Observe os símbolos, as escolhas e aquilo que deseja nascer.'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};
function go(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true');scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'',id==='home'?'./':`#${id}`)}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#menuBtn').onclick=()=>{$('#drawer').classList.add('open');$('#drawer').setAttribute('aria-hidden','false')};$('#closeMenu').onclick=()=>$('#drawer').classList.remove('open');$('#orb').onclick=()=>go('tarot');

// Fundo estelar leve
{const c=$('#stars'),x=c.getContext('2d');let stars=[];function size(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;stars=Array.from({length:Math.min(150,innerWidth/3)},()=>({x:Math.random()*c.width,y:Math.random()*c.height,r:Math.random()*2+.3,a:Math.random()}))}function draw(){x.clearRect(0,0,c.width,c.height);stars.forEach(s=>{s.a+=.008;x.fillStyle=`rgba(230,210,255,${.15+Math.sin(s.a)*.15})`;x.beginPath();x.arc(s.x,s.y,s.r,0,7);x.fill()});requestAnimationFrame(draw)}addEventListener('resize',size);size();draw()}

// Orbe fluida: luz ligada diretamente ao toque, inércia e ondas
{const c=$('#orbCanvas'),x=c.getContext('2d');let w=0,p={x:.4,y:.35},v={x:0,y:0},target={...p},ripples=[],down=false,t=0;function size(){w=c.width=Math.round(c.clientWidth*devicePixelRatio);c.height=w}function pos(e){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}c.addEventListener('pointerdown',e=>{down=true;c.setPointerCapture(e.pointerId);target=pos(e);ripples.push({...target,a:1})});c.addEventListener('pointermove',e=>{if(down)target=pos(e)});c.addEventListener('pointerup',()=>down=false);function blob(cx,cy,r,color){const g=x.createRadialGradient(cx,cy,0,cx,cy,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');x.fillStyle=g;x.fillRect(0,0,w,w)}function frame(){t+=.012;v.x+=(target.x-p.x)*.045;v.y+=(target.y-p.y)*.045;v.x*=.9;v.y*=.9;p.x+=v.x;p.y+=v.y;if(!down){target.x=.5+Math.sin(t*.7)*.16;target.y=.46+Math.cos(t*.83)*.13}x.clearRect(0,0,w,w);x.save();x.beginPath();x.arc(w/2,w/2,w*.49,0,7);x.clip();const bg=x.createRadialGradient(w*.36,w*.28,w*.02,w*.5,w*.5,w*.68);bg.addColorStop(0,'#fff');bg.addColorStop(.12,'#63eaff');bg.addColorStop(.35,'#ef50d1');bg.addColorStop(.62,'#54229f');bg.addColorStop(1,'#050211');x.fillStyle=bg;x.fillRect(0,0,w,w);blob(p.x*w,p.y*w,w*.34,'rgba(255,255,255,.68)');blob((.5+Math.sin(t)*.24)*w,(.5+Math.cos(t*.8)*.22)*w,w*.45,'rgba(253,38,194,.5)');blob((.52+Math.cos(t*.73)*.27)*w,(.5+Math.sin(t*1.1)*.2)*w,w*.38,'rgba(53,225,255,.38)');ripples=rpples(ripples);x.restore();x.strokeStyle='rgba(235,204,255,.45)';x.lineWidth=w*.008;x.beginPath();x.arc(w/2,w/2,w*.485,0,7);x.stroke();requestAnimationFrame(frame)}function rpples(a){return a.filter(r=>{r.a-=.018;const radius=(1-r.a)*w*.35;x.strokeStyle=`rgba(255,255,255,${r.a*.55})`;x.lineWidth=w*.006*r.a;x.beginPath();x.arc(r.x*w,r.y*w,radius,0,7);x.stroke();return r.a>0})}size();addEventListener('resize',size);frame()}

// Tarot Livre: 78 cartas sem repetição e sem significados
let session=JSON.parse(localStorage.getItem('orbe-free-deck')||'null');
function shuffledDeck(){const a=cards.map(c=>c.id);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function fresh(){return{order:shuffledDeck(),shown:[],reversed:[]}}
if(!session||!Array.isArray(session.order)||new Set([...session.order,...session.shown]).size!==78)session=fresh();
function saveDeck(){localStorage.setItem('orbe-free-deck',JSON.stringify(session))}
function showCard(id,rev=false){const c=cards[id],box=$('#current');box.className=`current revealing${rev?' reversed':''}`;box.innerHTML=`<img src="${c.image}" alt="${c.name}">`;$('#cardCaption').textContent=`${c.name} · ${rev?'posição invertida':'posição direta'}`;setTimeout(()=>box.classList.remove('revealing'),720)}
function renderDeck(){const n=session.shown.length;$('#count').innerHTML=`${n}<small>/78</small>`;$('#memory').innerHTML=session.shown.map((id,i)=>`<button data-history="${i}" aria-label="Rever ${cards[id].name}"><img src="${cards[id].image}" alt=""></button>`).join('');$$('[data-history]').forEach(b=>b.onclick=()=>{const i=+b.dataset.history;showCard(session.shown[i],session.reversed[i])});$('#resetDeck').hidden=n<78;if(n)showCard(session.shown.at(-1),session.reversed.at(-1))}
$('#nextCard').onclick=()=>{if(!session.order.length)return toast('O baralho foi concluído.');const id=session.order.shift(),rev=Math.random()<.22;session.shown.push(id);session.reversed.push(rev);saveDeck();renderDeck();navigator.vibrate?.(18)};$('#resetDeck').onclick=()=>{session=fresh();saveDeck();$('#current').className='current empty';$('#current').innerHTML='<span>Toque em “Próxima carta”</span>';$('#cardCaption').textContent='No Tarot Livre, a imagem fala por si.';renderDeck()};renderDeck();

// Carta do Dia: única área individual com significado
function todayKey(){return new Date().toLocaleDateString('pt-BR')}
$('#drawDaily').onclick=()=>{let d=JSON.parse(localStorage.getItem('orbe-daily')||'null');if(!d||d.date!==todayKey())d={date:todayKey(),id:Math.floor(Math.random()*78),rev:Math.random()<.18,intention:$('#dailyIntention').value.trim()};localStorage.setItem('orbe-daily',JSON.stringify(d));renderDaily(d);navigator.vibrate?.([20,35,30])};
function renderDaily(d){const c=cards[d.id],key=c.suit||'Maior';$('#dailyCard').innerHTML=`${d.intention?`<p class="intention">Sua intenção · ${d.intention.replace(/[<>]/g,'')}</p>`:''}<div class="daily-reveal"><img class="${d.rev?'reversed':''}" src="${c.image}" alt="${c.name}"></div><h3>${c.name}</h3><p class="caption">${d.rev?'Posição invertida':'Posição direta'} · ${c.arcana}</p><div class="panel"><p>${dailyMeanings[key]}</p><p><em>Pergunta do dia:</em> o que esta carta convida você a reconhecer agora?</p></div><button class="primary" data-save-daily>Guardar no diário</button>`;$('[data-save-daily]').onclick=()=>addEntry(`Carta do Dia — ${c.name}: ${dailyMeanings[key]}`)}
{const d=JSON.parse(localStorage.getItem('orbe-daily')||'null');if(d?.date===todayKey())renderDaily(d)}

// Tiragens com significado
const spreads=[['Uma Carta',1],['Passado · Presente · Tendência',3],['Situação · Ação · Resultado',3],['Amor',3],['Dois Caminhos',5],['Cruz Celta',10]];
$('#spreadGrid').innerHTML=spreads.map((s,i)=>`<button data-spread="${i}">${s[0]}<small>${s[1]} carta${s[1]>1?'s':''}</small></button>`).join('');$$('[data-spread]').forEach(b=>b.onclick=()=>{const s=spreads[+b.dataset.spread],ids=cards.map(c=>c.id).sort(()=>Math.random()-.5).slice(0,s[1]);$('#spreadResult').innerHTML=`<h3>${s[0]}</h3><div class="spread-cards">${ids.map(id=>`<figure><img src="${cards[id].image}" alt="${cards[id].name}"><figcaption>${cards[id].name}</figcaption></figure>`).join('')}</div><p>${ids.map(id=>dailyMeanings[cards[id].suit||'Maior']).join(' ')}</p>`;$('#spreadResult').scrollIntoView({behavior:'smooth'})});

// Whit local segura; chave real deve ficar no servidor
$('#chatForm').onsubmit=e=>{e.preventDefault();const input=$('#chatInput'),q=input.value.trim();if(!q)return;$('#chat').insertAdjacentHTML('beforeend',`<p class="bubble user">${q.replace(/[<>]/g,'')}</p>`);input.value='';setTimeout(()=>{$('#chat').insertAdjacentHTML('beforeend','<p class="bubble bot">Respire e observe a palavra que mais pulsa na sua pergunta. A Orbe pode ajudar a organizar esse símbolo; a conexão com IA segura será ativada pelo servidor.</p>');$('#chat').scrollTop=$('#chat').scrollHeight},450)};

const products=[['Deck Orbe das Realidades','R$ 199'],['Leitura digital personalizada','R$ 100'],['Caderno Ritual da Orbe','R$ 79'],['Arte exclusiva de Arcano','R$ 149']];
const services=[['Mesa Real','R$ 200'],['Leitura de Mentes','R$ 200'],['Carta de Conselho','R$ 100']];
const plans=[['Presença','Grátis'],['Orbe Lunar','R$ 19,90/mês'],['Orbe Suprema','R$ 39,90/mês']];
function commerce(el,data,action){$(el).innerHTML=data.map(x=>`<article class="panel"><h3>${x[0]}</h3><p class="price">${x[1]}</p><button class="primary" data-action>${action}</button></article>`).join('');$$(el+' [data-action]').forEach(b=>b.onclick=()=>toast('Estrutura pronta para conectar ao pagamento seguro.'))}commerce('#products',products,'Ver produto');commerce('#services',services,'Agendar consulta');commerce('#plans',plans,'Escolher plano');

const saved=()=>JSON.parse(localStorage.getItem('orbe-journal')||'[]');function addEntry(text){const e=saved();e.unshift({text,date:new Date().toLocaleString('pt-BR')});localStorage.setItem('orbe-journal',JSON.stringify(e));renderEntries();toast('Guardado no Diário da Orbe')}function renderEntries(){$('#entries').innerHTML=saved().map(e=>`<article><small>${e.date}</small><p>${e.text.replace(/[<>]/g,'')}</p></article>`).join('')}$('#journalForm').onsubmit=e=>{e.preventDefault();addEntry($('#journalText').value);$('#journalText').value=''};renderEntries();

const settings=JSON.parse(localStorage.getItem('orbe-settings')||'{}');$('#youtubeLink').href=settings.youtube||CONFIG.youtube;$('#spotifyLink').href=CONFIG.spotify;$('#userLogin').onsubmit=e=>{e.preventDefault();toast('A estrutura de conta está pronta para o servidor seguro.')};$('#adminLogin').onsubmit=e=>{e.preventDefault();if($('#adminUser').value===CONFIG.adminUser){$('#adminLogin').hidden=true;$('#adminPanel').hidden=false;$('#adminYoutube').value=settings.youtube||CONFIG.youtube;$('#adminWhatsapp').value=settings.whatsapp||CONFIG.whatsapp}else $('#adminMsg').textContent='Login não reconhecido. A autenticação real será validada no servidor.'};$('#saveSettings').onclick=()=>{localStorage.setItem('orbe-settings',JSON.stringify({youtube:$('#adminYoutube').value,whatsapp:$('#adminWhatsapp').value}));toast('Configurações salvas neste aparelho')};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
let installPrompt=null;addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installApp').hidden=false});$('#installApp').onclick=async()=>{if(!installPrompt)return toast('No iPhone: Compartilhar → Adicionar à Tela de Início.');installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installApp').hidden=true};
const initial=location.hash.slice(1);if(initial&&document.getElementById(initial))go(initial);
