import { CONFIG } from './config.js';
import { escapeHTML } from './storage.js';
import { createNavigation } from './navigation.js?v=75';
import { RealityOrbEngine } from './orb-engine-v68.js?v=69';
import { bindMiniOrbs } from './mini-orb-engine.js?v=71';
import { FreeTarot } from './tarot-engine.js?v=85';
import { DailyRitual } from './ritual-engine.js';
import { CardLibraryEngine } from './card-library-engine.js';
import { SchoolEngine } from './school-engine.js';
import { PremiumEngine } from './premium-engine.js';
import { SpreadsEngine } from './spreads-engine.js';
import { JournalEngine } from './journal-engine.js';
import { CommerceEngine } from './commerce-engine.js';
import { MediaEngine } from './media-engine.js';
import { AIEngine } from './ai-engine.js';
import './tarot-image-runtime.js';

const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const toast = message => { const el=$('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.classList.remove('show'),2400); };
const { go } = createNavigation();
bindMiniOrbs();
const orb = new RealityOrbEngine($('#orbCanvas'),{onOpen:()=>go('tarot')});
new FreeTarot($('#tarot'));
const journal = new JournalEngine($('#journalForm'), $('#entries'), $('#mirrorStats'));
new DailyRitual($('#dailyCard'), entry => journal.add(entry));
new CardLibraryEngine($('#cardLibraryApp'));
new SchoolEngine($('#schoolApp'));
new SpreadsEngine($('#spreadGrid'), $('#spreadResult'), entry => journal.add(entry));
addEventListener('orbe:toast', event => toast(event.detail));
new CommerceEngine({store:$('#storeApp'),consultations:$('#consultationApp'),subscriptions:$('#subscriptionApp')},CONFIG);
new MediaEngine({videos:$('#videoApp'),music:$('#musicApp')},CONFIG);
new AIEngine($('#ai'),CONFIG);
new PremiumEngine($('#subscriptionApp'));

$('#userLogin').onsubmit=event=>{event.preventDefault();toast('Login seguro será ativado com o servidor.');};
$('#adminLogin').onsubmit=event=>{event.preventDefault();if($('#adminUser').value!==CONFIG.adminUser){$('#adminMsg').textContent='Login não reconhecido.';return;}$('#adminMsg').textContent='Usuário reconhecido. A senha será validada somente pelo servidor seguro — nunca pelo arquivo público.';};

let installPrompt=null;addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#installApp').hidden=false;});$('#installApp').onclick=async()=>{if(!installPrompt){toast('No iPhone: Compartilhar → Adicionar à Tela de Início.');return;}installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;};
if('serviceWorker' in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
window.orbe={go};
