import { store,escapeHTML } from './storage.js';
const money=value=>value==null?'Em breve':value===0?'Grátis':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
const emit=message=>dispatchEvent(new CustomEvent('orbe:toast',{detail:message}));
export class CommerceEngine{
  constructor(roots,config){this.roots=roots;this.config=config;this.cart=store.get('cart',[]);this.renderStore();this.renderConsultations();this.renderSubscriptions();}
  renderStore(){const products=this.config.products;this.roots.store.innerHTML=`<div class="shop-toolbar"><div><span>Seu pedido</span><strong data-cart-count>${this.cart.length} item${this.cart.length===1?'':'s'}</strong></div><button class="primary" data-open-cart>Ver sacola</button></div><div class="shop-grid">${products.map(p=>`<article class="product-card"><div class="product-symbol">${p.category.slice(0,1)}</div><small>${p.category}</small><h3>${p.name}</h3><p>${p.description}</p><strong>${money(p.price)}</strong><button class="primary" data-add="${p.id}" ${p.price==null?'disabled':''}>${p.price==null?'Entrar na lista':'Adicionar'}</button></article>`).join('')}</div><div class="cart-sheet" data-cart hidden></div>`;this.roots.store.onclick=e=>{const add=e.target.closest('[data-add]');if(add){this.cart.push(products.find(p=>p.id===add.dataset.add));store.set('cart',this.cart);this.renderStore();emit('Adicionado à sua sacola');return;}if(e.target.closest('[data-open-cart]'))this.showCart();};}
  showCart(){const box=this.roots.store.querySelector('[data-cart]');box.hidden=false;box.innerHTML=`<div class="cart-top"><h3>Sua sacola</h3><button data-close>×</button></div>${this.cart.length?this.cart.map((p,i)=>`<div class="cart-row"><span>${p.name}</span><strong>${money(p.price)}</strong><button data-remove="${i}">Remover</button></div>`).join(''):'<p>Sua sacola está vazia.</p>'}<div class="cart-total"><span>Total</span><strong>${money(this.cart.reduce((sum,p)=>sum+(p.price||0),0))}</strong></div><button class="primary" data-order ${this.cart.length?'':'disabled'}>Solicitar pedido</button>`;box.onclick=e=>{if(e.target.closest('[data-close]'))box.hidden=true;const remove=e.target.closest('[data-remove]');if(remove){this.cart.splice(+remove.dataset.remove,1);store.set('cart',this.cart);this.renderStore();this.showCart();}if(e.target.closest('[data-order]'))this.contact(`Olá! Quero solicitar este pedido da Loja da Orbe:\n${this.cart.map(p=>`• ${p.name} — ${money(p.price)}`).join('\n')}\nTotal: ${money(this.cart.reduce((s,p)=>s+(p.price||0),0))}`);};}
  renderConsultations(){this.roots.consultations.innerHTML=`<div class="service-grid">${this.config.services.map((s,i)=>`<article class="service-card"><span>0${i+1}</span><h3>${s.name}</h3><p>${s.description}</p><strong>${money(s.price)}</strong><button class="primary" data-service="${i}">Escolher consulta</button></article>`).join('')}</div><form class="booking panel" hidden><p class="eyebrow">SOLICITAR HORÁRIO</p><h3 data-book-title></h3><input name="name" required placeholder="Seu nome"><input name="contact" required placeholder="WhatsApp ou e-mail"><textarea name="question" required placeholder="Conte brevemente o tema da consulta"></textarea><button class="primary">Enviar solicitação</button></form>`;const form=this.roots.consultations.querySelector('form');this.roots.consultations.onclick=e=>{const b=e.target.closest('[data-service]');if(!b)return;form.hidden=false;form.dataset.service=b.dataset.service;form.querySelector('[data-book-title]').textContent=this.config.services[+b.dataset.service].name;form.scrollIntoView({behavior:'smooth'});};form.onsubmit=e=>{e.preventDefault();const service=this.config.services[+form.dataset.service],data=new FormData(form);this.contact(`Olá! Quero solicitar ${service.name} (${money(service.price)}).\nNome: ${data.get('name')}\nContato: ${data.get('contact')}\nTema: ${data.get('question')}`);};}
  renderSubscriptions(){this.roots.subscriptions.innerHTML=`<div class="plan-grid">${this.config.plans.map((p,i)=>`<article class="plan-card ${i===1?'featured':''}">${i===1?'<small class="recommended">MAIS ESCOLHIDO</small>':''}<h3>${p.name}</h3><p>${p.description}</p><strong>${money(p.price)}</strong><span>${p.cycle}</span><button class="primary" data-plan="${i}">${p.price?'Quero este plano':'Plano atual'}</button></article>`).join('')}</div><p class="security-note">As cobranças só serão liberadas quando o checkout seguro estiver configurado. Nenhum cartão é solicitado nesta versão.</p>`;this.roots.subscriptions.onclick=e=>{const b=e.target.closest('[data-plan]');if(!b)return;const p=this.config.plans[+b.dataset.plan];p.price?this.contact(`Olá! Tenho interesse na assinatura ${p.name}, ${money(p.price)} ${p.cycle}.`):emit('O plano Presença já está disponível.');};}
  contact(message){if(this.config.whatsapp){open(`https://wa.me/${this.config.whatsapp.replace(/\D/g,'')}?text=${encodeURIComponent(message)}`,'_blank','noopener');return;}if(this.config.contactEmail){location.href=`mailto:${this.config.contactEmail}?subject=${encodeURIComponent('Orbe das Realidades')}&body=${encodeURIComponent(message)}`;return;}navigator.clipboard?.writeText(message);emit('Pedido preparado e copiado. Adicione WhatsApp ou e-mail em config.js para envio automático.');}
}
