import { store, escapeHTML } from './storage.js';
const money=value=>value==null?'Ver valor no parceiro':value===0?'Grátis':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
const emit=message=>dispatchEvent(new CustomEvent('orbe:toast',{detail:message}));
export class CommerceEngine{
  constructor(roots,config){this.roots=roots;this.config=config;this.query='';this.category='Todos';this.onlyFavorites=false;this.favorites=new Set(store.get('affiliateFavorites',[]));this.renderStore();this.renderConsultations();this.renderSubscriptions();}
  affiliateURL(product){const base=product.url||`https://www.amazon.com.br/s?k=${encodeURIComponent(product.search||product.name)}`,tag=String(this.config.amazonAssociateTag||'').trim();if(!tag||tag==='SEU-CODIGO-20')return base;try{const url=new URL(base);url.searchParams.set('tag',tag);return url.toString();}catch{return base;}}
  visibleProducts(){const text=this.query.toLocaleLowerCase('pt-BR');return this.config.products.filter(product=>{const haystack=[product.name,product.category,product.description,...(product.tags||[])].join(' ').toLocaleLowerCase('pt-BR');return(!text||haystack.includes(text))&&(this.category==='Todos'||product.category===this.category)&&(!this.onlyFavorites||this.favorites.has(product.id));});}
  renderStore(){const products=this.visibleProducts(),categories=['Todos',...new Set(this.config.products.map(product=>product.category))],ready=this.config.amazonAssociateTag&&this.config.amazonAssociateTag!=='SEU-CODIGO-20';this.roots.store.innerHTML=`
    <aside class="affiliate-notice"><span>TRANSPARÊNCIA</span><p>Como associado da Amazon, eu recebo por compras qualificadas. A compra, o pagamento, a entrega e o suporte acontecem no site do parceiro.</p></aside>
    ${ready?'':'<aside class="setup-warning"><strong>Ative suas comissões</strong><p>Abra <code>config.js</code> e troque <code>SEU-CODIGO-20</code> pelo seu código aprovado no Programa de Associados da Amazon.</p></aside>'}
    <div class="shop-controls"><label class="shop-search"><span>Buscar na curadoria</span><input type="search" value="${escapeHTML(this.query)}" placeholder="Tarot, cristais, livros..." data-shop-search></label><button class="favorites-filter ${this.onlyFavorites?'active':''}" data-favorites-only aria-pressed="${this.onlyFavorites}">♡ Favoritos <b>${this.favorites.size}</b></button></div>
    <div class="category-rail" aria-label="Categorias">${categories.map(category=>`<button class="${category===this.category?'active':''}" data-category="${escapeHTML(category)}">${escapeHTML(category)}</button>`).join('')}</div>
    <p class="shop-results">${products.length} ${products.length===1?'escolha encontrada':'escolhas encontradas'}</p><div class="affiliate-grid">${products.map(product=>this.productCard(product)).join('')}</div>
    ${products.length?'':'<div class="empty-shop"><span>✦</span><h3>Nenhuma escolha apareceu.</h3><p>Limpe a busca ou veja todas as categorias.</p><button data-clear-shop>Mostrar tudo</button></div>'}<p class="affiliate-legal">Os valores e a disponibilidade podem mudar no site do parceiro. Esta vitrine não cobra nem armazena dados de pagamento.</p>`;this.bindStore();}
  productCard(product){const favorite=this.favorites.has(product.id);return`<article class="affiliate-product ${product.featured?'featured':''}"><div class="product-art" aria-hidden="true"><i>${escapeHTML(product.symbol||'✦')}</i><span>${escapeHTML(product.category)}</span></div><button class="favorite-button ${favorite?'active':''}" data-favorite="${escapeHTML(product.id)}" aria-label="${favorite?'Remover dos':'Adicionar aos'} favoritos" aria-pressed="${favorite}">${favorite?'♥':'♡'}</button>${product.featured?'<span class="product-badge">ESCOLHA DA ORBE</span>':''}<p class="product-category">${escapeHTML(product.category)}</p><h3>${escapeHTML(product.name)}</h3><p>${escapeHTML(product.description)}</p>${product.note?`<small class="product-meta">${escapeHTML(product.note)}</small>`:''}<a class="affiliate-buy" data-affiliate="${escapeHTML(product.id)}" href="${escapeHTML(this.affiliateURL(product))}" target="_blank" rel="nofollow sponsored noopener"><span>${money(product.price)}</span><b>Ver produto ↗</b></a><small class="sponsored-label">LINK PATROCINADO · COMPRA NO PARCEIRO</small></article>`;}
  bindStore(){const root=this.roots.store;root.querySelector('[data-shop-search]')?.addEventListener('input',event=>{this.query=event.target.value;this.renderStore();requestAnimationFrame(()=>{const input=root.querySelector('[data-shop-search]');input?.focus();input?.setSelectionRange(this.query.length,this.query.length);});});root.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{this.category=button.dataset.category;this.renderStore();}));root.querySelector('[data-favorites-only]')?.addEventListener('click',()=>{this.onlyFavorites=!this.onlyFavorites;this.renderStore();});root.querySelector('[data-clear-shop]')?.addEventListener('click',()=>{this.query='';this.category='Todos';this.onlyFavorites=false;this.renderStore();});root.querySelectorAll('[data-favorite]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.favorite;this.favorites.has(id)?this.favorites.delete(id):this.favorites.add(id);store.set('affiliateFavorites',[...this.favorites]);this.renderStore();emit(this.favorites.has(id)?'Guardado nos favoritos':'Removido dos favoritos');}));root.querySelectorAll('[data-affiliate]').forEach(link=>link.addEventListener('click',()=>{const clicks=store.get('affiliateClicks',{});clicks[link.dataset.affiliate]=(clicks[link.dataset.affiliate]||0)+1;store.set('affiliateClicks',clicks);}));}
  renderConsultations(){this.roots.consultations.innerHTML=`<div class="service-grid">${this.config.services.map((s,i)=>`<article class="service-card"><span>0${i+1}</span><h3>${escapeHTML(s.name)}</h3><p>${escapeHTML(s.description)}</p><strong>${money(s.price)}</strong><button class="primary" data-service="${i}">Escolher consulta</button></article>`).join('')}</div><form class="booking panel" hidden><p class="eyebrow">SOLICITAR HORÁRIO</p><h3 data-book-title></h3><input name="name" required placeholder="Seu nome"><input name="contact" required placeholder="WhatsApp ou e-mail"><textarea name="question" required placeholder="Conte brevemente o tema da consulta"></textarea><button class="primary">Enviar solicitação</button></form>`;const form=this.roots.consultations.querySelector('form');this.roots.consultations.onclick=e=>{const b=e.target.closest('[data-service]');if(!b)return;form.hidden=false;form.dataset.service=b.dataset.service;form.querySelector('[data-book-title]').textContent=this.config.services[+b.dataset.service].name;form.scrollIntoView({behavior:'smooth'});};form.onsubmit=e=>{e.preventDefault();const service=this.config.services[+form.dataset.service],data=new FormData(form);this.contact(`Olá! Quero solicitar ${service.name} (${money(service.price)}).\nNome: ${data.get('name')}\nContato: ${data.get('contact')}\nTema: ${data.get('question')}`);};}
  renderSubscriptions(){this.roots.subscriptions.innerHTML=`<div class="plan-grid">${this.config.plans.map((p,i)=>`<article class="plan-card ${i===1?'featured':''}">${i===1?'<small class="recommended">MAIS ESCOLHIDO</small>':''}<h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.description)}</p><strong>${money(p.price)}</strong><span>${escapeHTML(p.cycle)}</span><button class="primary" data-plan="${i}">${p.price?'Quero este plano':'Plano atual'}</button></article>`).join('')}</div><p class="security-note">As cobranças só serão liberadas quando o checkout seguro estiver configurado. Nenhum cartão é solicitado nesta versão.</p>`;this.roots.subscriptions.onclick=e=>{const b=e.target.closest('[data-plan]');if(!b)return;const p=this.config.plans[+b.dataset.plan];p.price?this.contact(`Olá! Tenho interesse na assinatura ${p.name}, ${money(p.price)} ${p.cycle}.`):emit('O plano Presença já está disponível.');};}
  contact(message){if(this.config.whatsapp){open(`https://wa.me/${this.config.whatsapp.replace(/\D/g,'')}?text=${encodeURIComponent(message)}`,'_blank','noopener');return;}if(this.config.contactEmail){location.href=`mailto:${this.config.contactEmail}?subject=${encodeURIComponent('Orbe das Realidades')}&body=${encodeURIComponent(message)}`;return;}navigator.clipboard?.writeText(message);emit('Solicitação copiada. Adicione WhatsApp ou e-mail em config.js para envio automático.');}
}
