import { store, escapeHTML } from './storage.js';
import { CONSULTATION_POLICY } from './consultation-policy.js';
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
const emit=message=>dispatchEvent(new CustomEvent('orbe:toast',{detail:message}));
const DRAFT='consultation-draft-v5';
export class ConsultationEngine{
  constructor(root){this.root=root;if(!root)return;this.selected=store.get(DRAFT)?.serviceId||'';this.render();}
  render(){const draft=store.get(DRAFT)||{};this.root.innerHTML=`<div class="consultation-v5"><aside class="consultation-notice"><strong>ATENDIMENTO HUMANO · E-MAIL SEGURO</strong><p>Escolha uma experiência e envie sua solicitação diretamente para <b>${CONSULTATION_POLICY.contactEmail}</b>. Não usamos WhatsApp nesta etapa. Nenhuma cobrança é feita aqui.</p></aside><div class="consultation-services" role="list" aria-label="Serviços de consulta">${CONSULTATION_POLICY.services.map((s,i)=>`<button type="button" class="consultation-service ${this.selected===s.id?'is-selected':''}" data-service="${s.id}" role="listitem"><small>0${i+1} · DISPONIBILIDADE</small><h3>${escapeHTML(s.name)}</h3><p>${escapeHTML(s.detail)}</p><strong>${money(s.price)}</strong></button>`).join('')}</div><form class="consultation-form" ${this.selected?'':'hidden'} novalidate><p class="eyebrow">SOLICITAR HORÁRIO</p><h3 data-selected-title></h3><label>Nome completo<input name="name" autocomplete="name" required value="${escapeHTML(draft.name||'')}" placeholder="Como deseja ser chamada"></label><label>E-mail<input name="email" type="email" autocomplete="email" required value="${escapeHTML(draft.email||'')}" placeholder="seu@email.com"></label><label>Telefone<input name="phone" type="tel" autocomplete="tel" required value="${escapeHTML(draft.phone||'')}" placeholder="(00) 00000-0000"></label><label>Data preferida<input name="date" type="date" value="${escapeHTML(draft.date||'')}"></label><label>Pergunta ou contexto<textarea name="question" required placeholder="Conte brevemente o que deseja iluminar">${escapeHTML(draft.question||'')}</textarea></label><div class="consultation-actions"><button type="submit" class="primary">Enviar por e-mail</button><button type="button" class="ghost" data-clear>Limpar</button></div><p class="consultation-status" data-status>Seu rascunho é salvo somente neste dispositivo até você enviar.</p></form></div>`;this.bind();}
  bind(){const form=this.root.querySelector('form');const title=this.root.querySelector('[data-selected-title]');const status=this.root.querySelector('[data-status]');const syncTitle=()=>{const s=CONSULTATION_POLICY.services.find(x=>x.id===this.selected);if(title)title.textContent=s?`${s.name} · ${money(s.price)}`:'';};syncTitle();this.root.querySelectorAll('[data-service]').forEach(b=>b.addEventListener('click',()=>{this.selected=b.dataset.service;this.render();this.root.querySelector('form')?.scrollIntoView({behavior:'smooth',block:'center'});}));form?.addEventListener('input',()=>{const data=Object.fromEntries(new FormData(form));store.set(DRAFT,{...data,serviceId:this.selected});});form?.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));const service=CONSULTATION_POLICY.services.find(x=>x.id===this.selected);if(!service)return;if(!data.name?.trim()||!data.email?.includes('@')||!data.phone?.trim()||!data.question?.trim()){status.textContent='Preencha nome, e-mail, telefone e pergunta para continuar.';status.className='consultation-status error';return;}const body=`Olá! Quero solicitar ${service.name} (${money(service.price)}).\n\nNome: ${data.name}\nE-mail: ${data.email}\nTelefone: ${data.phone}\nData preferida: ${data.date||'a combinar'}\nPergunta ou contexto: ${data.question}\n\nEnviado pelo site Divina Bruxa — ambiente sandbox.`;store.set(DRAFT,{...data,serviceId:this.selected,submittedAt:new Date().toISOString()});location.href=`mailto:${CONSULTATION_POLICY.contactEmail}?subject=${encodeURIComponent(`Consulta Divina Bruxa — ${service.name}`)}&body=${encodeURIComponent(body)}`;status.textContent='Seu aplicativo de e-mail foi aberto com a solicitação pronta para revisão e envio.';status.className='consultation-status success';emit('Solicitação preparada no seu e-mail.');});this.root.querySelector('[data-clear]')?.addEventListener('click',()=>{store.remove?.(DRAFT);localStorage.removeItem(`divina:${DRAFT}`);this.selected='';this.render();});}
}
