import { CARDS } from './tarot-data.js';import { store,escapeHTML } from './storage.js';
export class JournalEngine{
 constructor(form,list,mirror){this.form=form;this.list=list;this.mirror=mirror;this.search='';this.form.onsubmit=e=>{e.preventDefault();const d=new FormData(this.form);this.add({title:d.get('title'),mood:d.get('mood'),question:d.get('question'),text:d.get('text'),tags:d.get('tags'),type:'note'});this.form.reset();};document.querySelector('#journalSearch')?.addEventListener('input',e=>{this.search=e.target.value.toLocaleLowerCase('pt-BR');this.render();});document.querySelector('#exportJournal')?.addEventListener('click',()=>this.export());this.render();}
 all(){return store.get('journal',[]);}
 add(entry){const all=this.all();all.unshift({...entry,date:new Date().toISOString()});store.set('journal',all);this.render();dispatchEvent(new CustomEvent('orbe:toast',{detail:'Guardado no Diário da Orbe'}));}
 render(){const all=this.all(),shown=all.map((e,i)=>({...e,_index:i})).filter(e=>!this.search||[e.title,e.text,e.question,e.tags,e.mood].join(' ').toLocaleLowerCase('pt-BR').includes(this.search));this.list.innerHTML=shown.length?shown.map(e=>`<article class="journal-entry">${e.cardId!=null?`<img src="${CARDS[e.cardId].image}" alt="">`:''}<div><small>${new Date(e.date).toLocaleString('pt-BR')} · ${escapeHTML(e.mood||'Reflexão')}</small><h3>${escapeHTML(e.title||'Memória da Orbe')}</h3>${e.question?`<p><b>Intenção:</b> ${escapeHTML(e.question)}</p>`:''}<p>${escapeHTML(e.text).replace(/\n/g,'<br>')}</p>${e.tags?`<span class="journal-tags">${escapeHTML(e.tags)}</span>`:''}<button data-delete="${e._index}">Excluir</button></div></article>`).join(''):'<p class="empty-state">Nenhuma memória encontrada.</p>';this.list.onclick=e=>{const b=e.target.closest('[data-delete]');if(!b)return;if(!confirm('Excluir esta memória?'))return;const next=this.all();next.splice(+b.dataset.delete,1);store.set('journal',next);this.render();};this.renderMirror(all);}
 export(){const blob=new Blob([JSON.stringify(this.all(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`diario-orbe-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 renderMirror(entries){const free=store.get('free-tarot',{revealed:[],reversed:[]}),ids=[...free.revealed,...entries.flatMap(e=>e.cardIds||[]),...entries.filter(e=>e.cardId!=null).map(e=>e.cardId)],counts={};ids.forEach(id=>counts[id]=(counts[id]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];const suits={Maiores:0,Copas:0,Espadas:0,Paus:0,Ouros:0};ids.forEach(id=>{if(CARDS[id])suits[CARDS[id].suit]++;});const dominant=Object.entries(suits).sort((a,b)=>b[1]-a[1])[0];const reversed=(free.reversed||[]).filter(Boolean).length;this.mirror.innerHTML=`<div><strong>${ids.length}</strong><span>cartas registradas</span></div><div><strong>${top?CARDS[top[0]].name:'—'}</strong><span>mais frequente</span></div><div><strong>${ids.length?dominant[0]:'—'}</strong><span>energia dominante</span></div><div><strong>${free.revealed?.length?Math.round(reversed/free.revealed.length*100):0}%</strong><span>invertidas no Tarot Livre</span></div>`;}
}
