import { CARDS } from './tarot-data.js';
import { store, escapeHTML } from './storage.js';
import { cardImageMarkup } from './tarot-image-runtime.js';
import { JOURNAL_STORAGE_KEY, JOURNAL_DRAFT_KEY, createJournalEntry, normalizeJournalEntries, publicMirrorData } from './journal-policy.js';

const safe = value => escapeHTML(value ?? '');
export class JournalEngine {
  constructor(form, list, mirror) {
    this.form=form; this.list=list; this.mirror=mirror; this.editingId=null;
    this.filters={query:'',mood:'',type:'',date:'',favorites:false};
    this.enhance(); this.bind(); this.restoreDraft(); this.render();
  }
  all(){return normalizeJournalEntries(store.get(JOURNAL_STORAGE_KEY,[]));}
  saveAll(entries){store.set(JOURNAL_STORAGE_KEY,entries);}
  enhance(){
    const submit=this.form.querySelector('button[type="submit"],button.primary');
    submit.insertAdjacentHTML('beforebegin','<label>Relacionamentos e pessoas relacionadas<input name="relationships" maxlength="300" placeholder="Opcional · nomes ou temas"></label><p class="journal-privacy">🔒 Privado por padrão. O texto não é enviado à IA, ao administrador ou ao analytics.</p>');
    document.querySelector('.journal-tools')?.insertAdjacentHTML('beforeend','<select id="journalMoodFilter" aria-label="Filtrar por humor"><option value="">Todos os humores</option><option>Em paz</option><option>Curiosa</option><option>Confiante</option><option>Em dúvida</option><option>Ansiosa</option><option>Em transformação</option><option>Reflexiva</option></select><select id="journalTypeFilter" aria-label="Filtrar por tipo"><option value="">Todos os tipos</option><option value="note">Anotações</option><option value="daily">Carta do Dia</option><option value="spread">Tiragens</option></select><input id="journalDateFilter" type="date" aria-label="Filtrar por data"><label class="journal-favorite-filter"><input id="journalFavoriteFilter" type="checkbox"> Somente favoritas</label>');
  }
  bind(){
    this.form.onsubmit=event=>{event.preventDefault();const data=Object.fromEntries(new FormData(this.form));const all=this.all();if(this.editingId){const index=all.findIndex(entry=>entry.id===this.editingId);if(index>=0)all[index]=createJournalEntry({...all[index],...data,id:this.editingId,createdAt:all[index].createdAt});}else all.unshift(createJournalEntry({...data,type:'note'}));this.saveAll(all);this.form.reset();this.editingId=null;store.remove(JOURNAL_DRAFT_KEY);this.form.querySelector('button.primary').textContent='Guardar no diário';this.render();dispatchEvent(new CustomEvent('orbe:toast',{detail:'Guardado no Diário da Orbe'}));};
    let timer=0;this.form.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>store.set(JOURNAL_DRAFT_KEY,Object.fromEntries(new FormData(this.form))),350);});
    const bind=(selector,key,event='input')=>document.querySelector(selector)?.addEventListener(event,({target})=>{this.filters[key]=target.type==='checkbox'?target.checked:target.value;this.render();});
    bind('#journalSearch','query');bind('#journalMoodFilter','mood','change');bind('#journalTypeFilter','type','change');bind('#journalDateFilter','date','change');bind('#journalFavoriteFilter','favorites','change');
    document.querySelector('#exportJournal')?.addEventListener('click',()=>this.export());
  }
  restoreDraft(){const draft=store.get(JOURNAL_DRAFT_KEY);if(!draft)return;for(const [name,value] of Object.entries(draft)){const field=this.form.elements.namedItem(name);if(field)field.value=value;}dispatchEvent(new CustomEvent('orbe:toast',{detail:'Rascunho do Diário restaurado'}));}
  add(entry){const all=this.all();all.unshift(createJournalEntry(entry));this.saveAll(all);this.render();dispatchEvent(new CustomEvent('orbe:toast',{detail:'Guardado no Diário da Orbe'}));}
  filtered(entries){const query=this.filters.query.trim().toLocaleLowerCase('pt-BR');return entries.filter(entry=>(!query||[entry.title,entry.text,entry.question,entry.tags,entry.mood,entry.relationships].join(' ').toLocaleLowerCase('pt-BR').includes(query))&&(!this.filters.mood||entry.mood===this.filters.mood)&&(!this.filters.type||entry.type===this.filters.type)&&(!this.filters.date||entry.createdAt.slice(0,10)===this.filters.date)&&(!this.filters.favorites||entry.favorite));}
  render(){const all=this.all();const shown=this.filtered(all);this.list.innerHTML=shown.length?shown.map(entry=>`<article class="journal-entry ${entry.favorite?'is-favorite':''}">${entry.cardId!==null?cardImageMarkup(CARDS[entry.cardId],{decorative:true}):''}<div><small>${new Date(entry.createdAt).toLocaleString('pt-BR')} · ${safe(entry.mood)}</small><h3>${safe(entry.title)}</h3>${entry.question?`<p><b>Intenção:</b> ${safe(entry.question)}</p>`:''}<p>${safe(entry.text).replace(/\n/g,'<br>')}</p>${entry.relationships?`<p><b>Relacionamentos:</b> ${safe(entry.relationships)}</p>`:''}${entry.tags?`<span class="journal-tags">${safe(entry.tags)}</span>`:''}<div class="journal-entry-actions"><button data-favorite="${entry.id}" aria-pressed="${entry.favorite}">${entry.favorite?'★ Favorita':'☆ Favoritar'}</button><button data-edit="${entry.id}">Editar</button><button data-delete="${entry.id}">Excluir</button></div></div></article>`).join(''):'<p class="empty-state">Nenhuma memória encontrada.</p>';this.list.onclick=event=>this.handleAction(event);this.renderMirror(all);}
  handleAction(event){const button=event.target.closest('[data-favorite],[data-edit],[data-delete]');if(!button)return;const id=button.dataset.favorite||button.dataset.edit||button.dataset.delete;const all=this.all();const index=all.findIndex(entry=>entry.id===id);if(index<0)return;if(button.dataset.favorite){all[index].favorite=!all[index].favorite;all[index].updatedAt=new Date().toISOString();this.saveAll(all);return this.render();}if(button.dataset.edit){this.editingId=id;for(const name of ['title','mood','question','text','tags','relationships']){const field=this.form.elements.namedItem(name);if(field)field.value=all[index][name]||'';}this.form.querySelector('button.primary').textContent='Salvar alterações';this.form.scrollIntoView({behavior:'smooth'});return;}if(!confirm('Excluir esta memória? Esta ação não pode ser desfeita.'))return;all.splice(index,1);this.saveAll(all);this.render();}
  export(){const payload={project:'Divina Bruxa',exportedAt:new Date().toISOString(),private:true,entries:this.all()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),anchor=document.createElement('a');anchor.href=URL.createObjectURL(blob);anchor.download=`diario-orbe-${new Date().toISOString().slice(0,10)}.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(anchor.href),1000);}
  renderMirror(entries){const aggregate=publicMirrorData(entries);const free=store.get('free-tarot',{revealed:[]});const ids=[...(free.revealed||[]),...aggregate.flatMap(entry=>entry.cardIds||[]),...aggregate.filter(entry=>entry.cardId!==null).map(entry=>entry.cardId)].filter(id=>CARDS[id]);const counts={};ids.forEach(id=>counts[id]=(counts[id]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];const suits={Maiores:0,Copas:0,Espadas:0,Paus:0,Ouros:0};ids.forEach(id=>suits[CARDS[id].suit]++);const dominant=Object.entries(suits).sort((a,b)=>b[1]-a[1])[0];const moods={};aggregate.forEach(entry=>moods[entry.mood]=(moods[entry.mood]||0)+1);const mood=Object.entries(moods).sort((a,b)=>b[1]-a[1])[0];this.mirror.innerHTML=`<div><strong>${entries.length}</strong><span>memórias privadas</span></div><div><strong>${top?safe(CARDS[top[0]].name):'—'}</strong><span>carta mais frequente</span></div><div><strong>${ids.length?safe(dominant[0]):'—'}</strong><span>naipe mais presente</span></div><div><strong>${mood?safe(mood[0]):'—'}</strong><span>humor mais registrado</span></div>`;}
}
