/* Orbe 3.0 — WebGL com fluido reativo, inércia e fallback Canvas */
(()=>{'use strict';const canvas=document.getElementById('orbCanvas'),orb=document.getElementById('orb'),label=document.getElementById('orbState');if(!canvas||!orb)return;const reduced=window.ORBE_CONFIG?.orb.reduced,quality=window.ORBE_CONFIG?.orb.quality||1;let gl,program,raf,visible=true,energy=.24,ripple=0,stateTimer,p={x:.5,y:.5,tx:.5,ty:.5,vx:0,vy:0,down:false},last={x:.5,y:.5,t:0};
const vertex=`attribute vec2 p;varying vec2 uv;void main(){uv=p*.5+.5;gl_Position=vec4(p,0.,1.);}`;
const fragment=`precision highp float;varying vec2 uv;uniform vec2 pointer;uniform vec2 drift;uniform float time;uniform float energy;uniform float ripple;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.)),f.x),f.y);}float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=a*noise(p);p=mat2(.8,-.6,.6,.8)*p*2.03;a*=.5;}return v;}
void main(){vec2 q=uv-.5;float d=length(q);if(d>.5)discard;float z=sqrt(max(0.,.25-d*d));vec2 sphere=q*(1.12+z*.42);vec2 touch=(pointer-.5)*vec2(1.,-1.);float t=time*.12;vec2 flow=sphere*3.4+drift*2.5;float n=fbm(flow+vec2(fbm(flow+t),fbm(flow-t)));float n2=fbm(flow*1.8+vec2(-t,t)+n);float wave=sin((length(q-touch)*34.)-time*4.)*exp(-length(q-touch)*9.)*ripple;float hue=n+n2*.55+wave*.22;vec3 cyan=vec3(.08,.83,1.),violet=vec3(.31,.08,1.),pink=vec3(1.,.08,.62),gold=vec3(1.,.62,.13);vec3 col=mix(violet,pink,smoothstep(.25,.78,hue));col=mix(col,cyan,smoothstep(.58,1.2,n2));col=mix(col,gold,smoothstep(.88,1.22,hue+energy*.12));float light=pow(max(0.,1.-length(q-touch)*1.8),4.)*energy;col+=vec3(.72,.94,1.)*light;float fres=pow(1.-z*2.,2.4);col+=vec3(.24,.18,.5)*fres;col*=.56+z*.92;col+=pow(max(0.,dot(normalize(vec3(q,z)),normalize(vec3(-.45,.55,1.)))),18.)*vec3(1.);float alpha=smoothstep(.5,.475,d);gl_FragColor=vec4(col,alpha);}`;
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}function webgl(){try{gl=canvas.getContext('webgl',{alpha:true,antialias:true,premultiplied:true});if(!gl)return false;program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vertex));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const a=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);return true}catch(e){console.warn('Orbe WebGL indisponível:',e);return false}}
function resize(){const r=orb.getBoundingClientRect(),scale=Math.min(quality,innerWidth<430?1.55:2);canvas.width=Math.max(280,Math.round(r.width*scale));canvas.height=canvas.width;if(gl)gl.viewport(0,0,canvas.width,canvas.height)}
function coords(e){const r=orb.getBoundingClientRect(),now=performance.now(),x=(e.clientX-r.left)/r.width,y=1-(e.clientY-r.top)/r.height,dt=Math.max(12,now-last.t||16);p.vx=(x-last.x)*16/dt;p.vy=(y-last.y)*16/dt;p.tx=Math.max(0,Math.min(1,x));p.ty=Math.max(0,Math.min(1,y));last={x,y,t:now};energy=1;ripple=1;label.textContent='tocando'}
orb.addEventListener('pointerdown',e=>{p.down=true;orb.setPointerCapture(e.pointerId);coords(e);navigator.vibrate?.(10)});orb.addEventListener('pointermove',e=>{if(p.down)coords(e)});orb.addEventListener('pointerup',()=>{p.down=false;setTimeout(()=>{if(label.textContent==='tocando')label.textContent='presença'},380)});orb.addEventListener('pointercancel',()=>p.down=false);orb.addEventListener('click',()=>{api.state('portal aberto',1);setTimeout(()=>window.go?.('explore'),330)});
let fallbackCtx=null,particles=[];function fallback(t){const c=fallbackCtx,w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);c.save();c.beginPath();c.arc(w/2,h/2,w*.49,0,Math.PI*2);c.clip();const g=c.createRadialGradient(p.x*w,(1-p.y)*h,0,w/2,h/2,w*.72);g.addColorStop(0,'#eaffff');g.addColorStop(.12,'#42deff');g.addColorStop(.38,'#7239ff');g.addColorStop(.67,'#d52b9c');g.addColorStop(1,'#080313');c.fillStyle=g;c.fillRect(0,0,w,h);c.globalCompositeOperation='screen';particles.forEach((x,i)=>{x.a+=x.s*(1+energy);const px=w/2+Math.cos(x.a+t*.00015)*w*x.r+p.vx*w*3,py=h/2+Math.sin(x.a*1.3)*h*x.r-p.vy*h*3,rg=c.createRadialGradient(px,py,0,px,py,w*x.z);rg.addColorStop(0,`hsla(${x.h},100%,80%,.7)`);rg.addColorStop(1,'transparent');c.fillStyle=rg;c.fillRect(0,0,w,h)});c.restore()}
function frame(ms){if(!visible)return;p.x+=(p.tx+p.vx*1.8-p.x)*.045;p.y+=(p.ty+p.vy*1.8-p.y)*.045;p.vx*=.94;p.vy*=.94;energy+=(p.down?1:.24-energy)*.035;ripple*=.965;if(gl){gl.useProgram(program);gl.uniform2f(gl.getUniformLocation(program,'pointer'),p.x,p.y);gl.uniform2f(gl.getUniformLocation(program,'drift'),p.vx,p.vy);gl.uniform1f(gl.getUniformLocation(program,'time'),ms*.001);gl.uniform1f(gl.getUniformLocation(program,'energy'),energy);gl.uniform1f(gl.getUniformLocation(program,'ripple'),ripple);gl.drawArrays(gl.TRIANGLES,0,6)}else fallback(ms);if(!reduced)raf=requestAnimationFrame(frame)}
const api=window.OrbeViva={state(text,power=.82){clearTimeout(stateTimer);label.textContent=text;energy=Math.max(energy,power);ripple=1;orb.dataset.state=text;stateTimer=setTimeout(()=>{label.textContent='presença';delete orb.dataset.state},1450)},pulse(power=1){energy=power;ripple=1}};
if(!webgl()){fallbackCtx=canvas.getContext('2d');particles=Array.from({length:34},(_,i)=>({a:Math.random()*6.28,r:.05+Math.random()*.36,s:.002+Math.random()*.005,z:.03+Math.random()*.08,h:[188,275,325,42][i%4]}))}resize();new ResizeObserver(resize).observe(orb);document.addEventListener('visibilitychange',()=>{visible=!document.hidden;if(visible&&!reduced){cancelAnimationFrame(raf);raf=requestAnimationFrame(frame)}});frame(0)})();
