import { store, escapeHTML } from './storage.js';
import { PREMIUM_POLICY } from './premium-policy.js';

const emit=message=>dispatchEvent(new CustomEvent('orbe:toast',{detail:message}));
const money=value=>value===0?'Grátis':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
export class PremiumEngine{
  constructor(root){this.root=root;this.state=store.get('billing-sandbox-v5',{entitlements:['presence'],purchases:[],skin:'classica'});this.render();}
  render(){this.root.innerHTML=`<div class="billing-sandbox"><span>AMBIENTE DE TESTES</span><p>Nenhum cartão, cobrança ou compra real é processado nesta versão.</p></div><div class="premium-plans">${PREMIUM_POLICY.plans.map(plan=>`<article class="premium-plan ${this.state.entitlements.includes(plan.id)?'owned':''}"><span>${this.state.entitlements.includes(plan.id)?'ATIVO':'PLANO'}</span><h3>${escapeHTML(plan.name)}</h3><p>${escapeHTML(plan.description)}</p><strong>${money(plan.price)}</strong><small>${escapeHTML(plan.cycle)}</small><button data-plan="${plan.id}">${plan.price?'Simular compra':'Plano atual'}</button></article>`).join('')}</div><div class="premium-actions"><button data-restore>Restaurar compras (sandbox)</button><button data-reset>Limpar sandbox</button></div><section class="skins-panel"><p class="eyebrow">SKINS DA ORBE</p><h3>Escolha uma atmosfera.</h3><div class="skin-grid">${PREMIUM_POLICY.skins.map(skin=>`<button data-skin="${skin.id}" class="${this.state.skin===skin.id?'active':''}" style="--skin-tone:${skin.tone}"><i></i><b>${escapeHTML(skin.name)}</b><small>${skin.status==='free'?'Grátis':'Premium'}</small></button>`).join('')}</div></section><p class="security-note">Billing real, Stripe, App Store e Google Play permanecem bloqueados até aprovação explícita e testes de reconciliação.</p>`;this.bind();}
  bind(){this.root.querySelectorAll('[data-plan]').forEach(button=>button.onclick=()=>{const plan=PREMIUM_POLICY.plans.find(item=>item.id===button.dataset.plan);if(!plan.price)return emit('O plano Presença já está disponível.');if(!this.state.entitlements.includes(plan.id))this.state.entitlements.push(plan.id);this.state.purchases.push({planId:plan.id,environment:'sandbox',at:new Date().toISOString()});store.set('billing-sandbox-v5',this.state);this.render();emit(`Compra simulada: ${plan.name}`);});this.root.querySelector('[data-restore]').onclick=()=>{store.set('billing-sandbox-v5',this.state);emit('Restauração sandbox concluída.');};this.root.querySelector('[data-reset]').onclick=()=>{if(!confirm('Limpar somente os dados de teste de billing?'))return;this.state={entitlements:['presence'],purchases:[],skin:'classica'};store.set('billing-sandbox-v5',this.state);this.render();};this.root.querySelectorAll('[data-skin]').forEach(button=>button.onclick=()=>{const skin=PREMIUM_POLICY.skins.find(item=>item.id===button.dataset.skin);if(skin.status==='premium'&&!this.state.entitlements.includes('premium'))return emit('Esta skin é Premium.');this.state.skin=skin.id;store.set('billing-sandbox-v5',this.state);document.body.dataset.orbeSkin=skin.id;this.render();});}
}
