import { store, escapeHTML } from './storage.js';
import { STORE_POLICY } from './store-policy.js';
const emit=message=>dispatchEvent(new CustomEvent('orbe:toast',{detail:message}));
export class StoreEngine{
  constructor(root,config){this.root=root;this.config=config;if(!root)return;this.query='';this.category='Todos';this.favorites=new Set(store.get('mystic-store-favorites-v5',[]));this.onlyFavorites=false;this.render();}
  url(product){const base=`https://www.amazon.com.br/s?k=${encodeURIComponent(product.search||product.name)}`;const tag=String(this.config.amazonAssociateTag||'').trim();if(!tag||tag==='SEU-CODIGO-20')return base;const url=new URL(base);url.searchParams.set('tag',tag);return url.toString();}
  products(){const query=this.query.toLocaleLowerCase('pt-BR');return this.config.products.filter(p=>{const content=[p.name,p.category,p.description,...(p.tags||[])].join(' ').toLocaleLowerCase('pt-BR');return(!query||content.includes(query))&&(this.category==='Todos'||p.category===this.category)&&(!this.onlyFavorites||this.favorites.has(p.id));});}
  render(){const products=this.products();this.root.innerHTML=`<div class="mystic-store-v5"><section class="store-cosmos"><div><p>CURADORIA DA ORBE</p><h3>Objetos para criar o seu universo.</h3><span>Tarot, livros, cristais, ritual, tecnologia e presentes escolhidos para sua jornada.</span></div><i aria-hidden="true">✦</i></section><aside class="store-disclosure"><strong>TRANSPARÊNCIA</strong><p>${escapeHTML(STORE_POLICY.disclosure)} A compra, o pagamento, a entrega e o suporte acontecem integralmente na Amazon.</p></aside><div class="store-controls"><label><span>BUSCAR NA LOJA</span><input type="search" data-search value="${escapeHTML(this.query)}" placeholder="Tarot, cristais, livros..."></label><button data-favorites aria-pressed="${this.onlyFavorites}" class="${this.onlyFavorites?'active':''}">♡ Favoritos <b>${this.favorites.size}</b></button></div><div class="store-categories" aria-label="Categorias">${STORE_POLICY.categories.map(c=>`<button data-category="${escapeHTML(c)}" class="${c===this.category?'active':''}">${escapeHTML(c)}</button>`).join('')}</div><p class="store-count">${products.length} ${products.length===1?'escolha encontrada':'escolhas encontradas'}</p><div class="store-grid">${products.map(p=>this.card(p)).join('')}</div>${products.length?'':`<div class="store-empty"><span>✦</span><h3>Nenhum item apareceu.</h3><button data-clear>Mostrar toda a curadoria</button></div>`}<p class="store-legal">PUBLICIDADE · Preços e disponibilidade podem mudar. A Divina Bruxa não recebe nem armazena dados de pagamento.</p></div>`;this.bind();}
  card(p){const favorite=this.favorites.has(p.id);return`<article class="store-product ${p.featured?'featured':''}"><div class="store-product-art" aria-hidden="true"><span>${escapeHTML(p.symbol||'✦')}</span><i></i></div><button class="store-heart ${favorite?'active':''}" data-favorite="${escapeHTML(p.id)}" aria-label="${favorite?'Remover dos':'Adicionar aos'} favoritos" aria-pressed="${favorite}">${favorite?'♥':'♡'}</button>${p.featured?'<em>ESCOLHA DA ORBE</em>':''}<small>${escapeHTML(p.category)}</small><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.description)}</p>${p.note?`<span class="store-note">${escapeHTML(p.note)}</span>`:''}<a href="${escapeHTML(this.url(p))}" data-affiliate="${escapeHTML(p.id)}" target="_blank" rel="nofollow sponsored noopener">Ver opções na Amazon <b>↗</b></a></article>`;}
  bind(){this.root.querySelector('[data-search]')?.addEventListener('input',e=>{this.query=e.target.value;this.render();requestAnimationFrame(()=>{const input=this.root.querySelector('[data-search]');input?.focus();input?.setSelectionRange(this.query.length,this.query.length);});});this.root.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{this.category=b.dataset.category;this.render();}));this.root.querySelector('[data-favorites]')?.addEventListener('click',()=>{this.onlyFavorites=!this.onlyFavorites;this.render();});this.root.querySelectorAll('[data-favorite]').forEach(b=>b.addEventListener('click',()=>{this.favorites.has(b.dataset.favorite)?this.favorites.delete(b.dataset.favorite):this.favorites.add(b.dataset.favorite);store.set('mystic-store-favorites-v5',[...this.favorites]);this.render();emit(this.favorites.has(b.dataset.favorite)?'Guardado nos favoritos':'Removido dos favoritos');}));this.root.querySelectorAll('[data-affiliate]').forEach(a=>a.addEventListener('click',()=>{const clicks=store.get('mystic-store-clicks-v5',{});clicks[a.dataset.affiliate]=(clicks[a.dataset.affiliate]||0)+1;store.set('mystic-store-clicks-v5',clicks);}));this.root.querySelector('[data-clear]')?.addEventListener('click',()=>{this.query='';this.category='Todos';this.onlyFavorites=false;this.render();});}
}
