create table if not exists products (id bigint generated by default as identity primary key, name text not null, price_cents integer not null default 0, description text, image_url text, buy_url text, active boolean default true, created_at timestamptz default now());
create table if not exists consultations (id bigint generated by default as identity primary key, service text not null, name text not null, email text not null, phone text not null, message text, status text default 'novo', created_at timestamptz default now());
create table if not exists episodes (id bigint generated by default as identity primary key, title text not null, description text, video_url text, cover_url text, published boolean default false, created_at timestamptz default now());
alter table products enable row level security; alter table consultations enable row level security; alter table episodes enable row level security;
create policy "public read active products" on products for select using (active = true);
create policy "public read episodes" on episodes for select using (published = true);
-- Crie políticas de escrita SOMENTE para o usuário administrador após definir o e-mail/UID do Admin.
