(()=>{'use strict';const q=document.getElementById('tarotQuestion'),begin=document.getElementById('beginReading'),draw=document.getElementById('draw'),status=document.getElementById('ritualStatus'),line=document.getElementById('ritualLine'),stage=document.querySelector('.card-stage'),deep=document.getElementById('deepReading'),deepen=document.getElementById('deepen'),favorite=document.getElementById('favorite'),save=document.getElementById('saveSingle'),share=document.getElementById('shareReading'),ring=document.querySelector('#deckRing strong');if(!draw)return;let ready=false;
function count(){const left=78-(Array.isArray(deck)?deck.length:0);ring.textContent=left;document.getElementById('deckCount').textContent=`${left} CARTAS RESTANTES NESTE CICLO`}count();function enable(on){[deepen,favorite,save,share].forEach(b=>b.disabled=!on)}function ritual(text,active=true){status.textContent=text;line.classList.toggle('active',active)}
begin.onclick=()=>{ready=true;ritual('A Orbe recebeu sua intenção');orbMode('ouvindo');q.blur();setTimeout(()=>ritual('Respire e revele quando sentir',false),950);draw.scrollIntoView({behavior:'smooth',block:'center'})};
draw.onclick=()=>{if(!ready){ready=true;ritual('Recebendo sua intenção');orbMode('ouvindo')}enable(false);deep.hidden=true;stage.classList.add('revealing');ritual('Embaralhando as 78 realidades');orbMode('embaralhando');document.getElementById('singleCard').classList.add('hidden-card');setTimeout(()=>{current=pick();current.question=q.value.trim();setCard(document.getElementById('singleCard'),current.id,current.rev);document.getElementById('singleTitle').textContent=current.name;document.getElementById('singleTags').innerHTML=`<span class="tag">${current.rev?'Invertida':'Direta'}</span><span class="tag">${suit(current.id)}</span>`;document.getElementById('singleMeaning').textContent=interpretation(current.id,current.rev);stage.classList.remove('revealing');ritual('Carta revelada',false);orbMode('revelando');enable(true);count();favorite.classList.toggle('favorite-on',favorites().some(x=>x.id===current.id));},900)};
function favorites(){return JSON.parse(localStorage.getItem('orbe-favorites')||'[]')}favorite.onclick=()=>{if(!current)return;let list=favorites(),i=list.findIndex(x=>x.id===current.id);if(i>=0){list.splice(i,1);favorite.classList.remove('favorite-on');toast('Removida das favoritas')}else{list.unshift({...current,saved:new Date().toLocaleString('pt-BR')});favorite.classList.add('favorite-on');toast('Carta favoritada')}localStorage.setItem('orbe-favorites',JSON.stringify(list))};
deepen.onclick=()=>{if(!current)return;const direction=current.rev?'Observe onde essa energia está bloqueada, exagerada ou voltada para dentro.':'Observe como essa energia já procura espaço para agir em sua vida.';deep.innerHTML=`<strong>Pergunta à sua realidade</strong><br>${current.question?`Em relação a “${current.question}”, `:''}${direction}<br><br><strong>Prática</strong><br>Escreva uma atitude pequena e possível que represente ${theme(current.id)} hoje.`;deep.hidden=false;orbMode('aprofundando')};
save.onclick=()=>{if(!current)return toast('Revele uma carta primeiro');saveEntry({...current,text:interpretation(current.id,current.rev)+(current.question?` Pergunta: ${current.question}`:'')});toast('Leitura guardada no Diário')};
share.onclick=async()=>{if(!current)return;const text=`Orbe das Realidades — ${current.name} (${current.rev?'invertida':'direta'}). ${interpretation(current.id,current.rev)}`;try{if(navigator.share)await navigator.share({title:'Minha leitura de Tarot',text,url:location.href});else{await navigator.clipboard.writeText(text);toast('Leitura copiada')}}catch(e){if(e.name!=='AbortError')toast('Não foi possível compartilhar')}};
document.getElementById('resetDeck').onclick=()=>{deck=[];localStorage.removeItem('orbe-deck');current=null;ready=false;q.value='';enable(false);deep.hidden=true;setCard(document.getElementById('singleCard'),0);document.getElementById('singleCard').classList.add('hidden-card');document.getElementById('singleTitle').textContent='A Orbe aguarda sua intenção';document.getElementById('singleMeaning').textContent='A carta surgirá quando sua intenção estiver pronta.';ritual('Aguardando sua intenção',false);count();toast('Novo ciclo de 78 cartas iniciado')};enable(false)})();
